/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/collections': typeof CollectionsRoute
  '/downloads': typeof DownloadsRoute
  '/profiles': typeof ProfilesRoute
  '/stats': typeof StatsRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/collections': typeof CollectionsRoute
  '/downloads': typeof DownloadsRoute
  '/profiles': typeof ProfilesRoute
  '/stats': typeof StatsRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/collections': typeof CollectionsRoute
  '/downloads': typeof DownloadsRoute
  '/profiles': typeof ProfilesRoute
  '/stats': typeof StatsRoute
  '/read/$bookId': typeof ReadBookIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collections'
    | '/downloads'
    | '/profiles'
    | '/stats'
    | '/read/$bookId'
    | '/series/$seriesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/collections'
    | '/downloads'
    | '/profiles'
    | '/stats'
    | '/read/$bookId'
    | '/series/$seriesId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/collections'
    | '/downloads'
    | '/profiles'
    | '/stats'
    | '/read/$bookId'
    | '/series/$seriesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CollectionsRoute: typeof CollectionsRoute
  DownloadsRoute: typeof DownloadsRoute
  ProfilesRoute: typeof ProfilesRoute
  StatsRoute: typeof StatsRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CollectionsRoute: CollectionsRoute,
  DownloadsRoute: DownloadsRoute,
  ProfilesRoute: ProfilesRoute,
  StatsRoute: StatsRoute,
  ReadBookIdRoute: ReadBookIdRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
